In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
FILEPATH = "/Users/raymondmbp/makeschool/DS-1.1-Data-Analysis/datasets/SA_Feedback_Surveys_FINAL/2016"
FILEPATH2 = "/Users/raymondmbp/makeschool/DS-1.1-Data-Analysis/datasets/SA_Feedback_Surveys_FINAL/2017"

import os
dir_path = os.path.dirname(os.path.realpath(FILEPATH))
dir_path

'/Users/raymondmbp/makeschool/DS-1.1-Data-Analysis/datasets/SA_Feedback_Surveys_FINAL'

# 2016 NPS analysis
## Data Exploration

In [3]:
import glob

all_csvs = glob.glob(os.path.join(FILEPATH, "*.csv"))
read_all_csvs = (pd.read_csv(f) for f in all_csvs)
df = pd.concat(read_all_csvs, ignore_index = True, sort = True)
df.head(5000)

#  \
0    NaN   
1    NaN   
2    NaN   
3    NaN   
4    NaN   
5    NaN   
6    NaN   
7    NaN   
8    NaN   
9    NaN   
10   NaN   
11   NaN   
12   NaN   
13   NaN   
14   NaN   
15   NaN   
16   NaN   
17   NaN   
18   NaN   
19   NaN   
20   NaN   
21   NaN   
22   NaN   
23   NaN   
24   NaN   
25   NaN   
26   NaN   
27   NaN   
28   NaN   
29   NaN   
..   ...   
962  NaN   
963  NaN   
964  NaN   
965  NaN   
966  NaN   
967  NaN   
968  NaN   
969  NaN   
970  NaN   
971  NaN   
972  NaN   
973  NaN   
974  NaN   
975  NaN   
976  NaN   
977  NaN   
978  NaN   
979  NaN   
980  NaN   
981  NaN   
982  NaN   
983  NaN   
984  NaN   
985  NaN   
986  NaN   
987  NaN   
988  NaN   
989  NaN   
990  NaN   
991  NaN   

     How likely is it that you would recommend the Make School Summer Academy to a friend?  \
0                                                  NaN                                       
1                                                  NaN                                       
2                                                  NaN                                       
3                                                  NaN                                       
4                                                  NaN                                       
5                                                  NaN                                       
6                                                  NaN                                       
7                                                  NaN                                       
8                                                  NaN                                       
9                                                  NaN                                       
10                                                 NaN                                       
11                                                 NaN                                       
12                                                 NaN                                       
13                                                 NaN                                       
14                                                 NaN                                       
15                                                 NaN                                       
16                                                 NaN                                       
17                                                 NaN                                       
18                                                 NaN                                       
19                                                 NaN                                       
20                                                 NaN                                       
21                                                 NaN                                       
22                                                 NaN                                       
23                                                 NaN                                       
24                                                 NaN                                       
25                                                 NaN                                       
26                                                 NaN                                       
27                                                 NaN                                       
28                                                 NaN                                       
29                                                 NaN                                       
..                                                 ...                                       
962                                                NaN                                       
963                                                NaN                                       
964                                                NaN            

In [4]:
df.isna().sum()

#                                                                                        927
How likely is it that you would recommend the Make School Summer Academy to a friend?    927
How well are the tutorials paced?                                                        776
How well is the schedule paced?                                                          281
How would you rate your overall satisfaction with the Summer Academy this week?           65
Network ID                                                                               927
Start Date (UTC)                                                                         927
Submit Date (UTC)                                                                        927
Timestamp                                                                                170
Unnamed: 0                                                                               930
What track are you in?                                                

# Plan of attack

- [ ] find out all the answers that don't answer a question and drop those
- [X] append location column to all files https://stackoverflow.com/questions/45211681/add-column-to-csv-file-and-insert-filename-in-that-column
- [X] delete #REF! columns
- [ ] multiply values in questions by 2 to conform with 2017 version
- [ ] combine "What track are you in?" with "track"

## There's overlap between "What track are you in?" and "track" columns. Combining results

In [5]:
df['track'].unique()

array([nan, 'summerApps', 'summerIntro', 'summerApps (4-week)',
       'summerGames', 'summerVR', 'summerGames (4-week)'], dtype=object)

In [6]:
df['What track are you in?'].unique()

array([nan, 'Intro', 'Games', 'Apps', 'VR', 'Average:'], dtype=object)

## Homogenizing results of two track columns

In [7]:
df.replace('summerApps', 'Apps', inplace = True)
df.replace('summerIntro', 'Intro', inplace = True)
df.replace('summerGames', 'Games', inplace = True)
df.replace('summerVR', 'VR', inplace = True)
df.replace('summerApps (4-week)', 'Apps', inplace = True)
df.replace('summerGames (4-week)', 'Games', inplace = True)

array([nan, 'Intro', 'Games', 'Apps', 'VR'], dtype=object)

## Dropping column that was Average: #REF! #REF!

In [25]:
df = df[df["What track are you in?"] != "Average:"]

In [34]:
# Sanity check to make sure items were replaced
df['track'].sort_values().unique()

array(['Apps', 'Games', 'Intro', 'VR', nan], dtype=object)

In [35]:
# Sanity check to make sure items were replaced
df['What track are you in?'].sort_values().unique()

array(['Apps', 'Games', 'Intro', 'VR', nan], dtype=object)

In [8]:
# TODO: Merge two columns
# df = df['track'].combine_first(df['What track are you in?'])


# df = pd.merge(df['What track are you in?'], df['track'], on='What track are you in?', how='outer')

# def combine_tracks(df):
#     df["track"] = df["track"].fillna("No Location")
#     df["What track are you in?"] = df["What track are you in?"].fillna("No Location")
#     df["Track_Full"] = df["What track are you in?"] + df["track"]
#     df.drop(columns=["What track are you in?", "track"], inplace=True)
#     return df

# for index, item in enumerate(df["Track_Full"]):
#     if item == "No LocationNo Location":
# #         df["Track_Full"][index] == "No Location"
# #         print(index, item)
#         df[df.loc[index]["Track_Full"]] = "No Location"

# df.merge(df['What track are you in?'], df['track'], on='What track are you in?', how='outer')
# df.concat([df['What track are you in?'], df['track']], axis = 1, ignore_index = True, sort = True)

In [9]:
df.tail()

#  \
986  NaN   
987  NaN   
989  NaN   
990  NaN   
991  NaN   

     How likely is it that you would recommend the Make School Summer Academy to a friend?  \
986                                                NaN                                       
987                                                NaN                                       
989                                                NaN                                       
990                                                NaN                                       
991                                                NaN                                       

     How well are the tutorials paced? How well is the schedule paced?  \
986                                NaN                               4   
987                                NaN                               4   
989                                NaN                               3   
990                                NaN                               3   
991                                NaN                               3   

    How would you rate your overall satisfaction with the Summer Academy this week?  \
986                                                  4                                
987                                                  4                                
989                                                  5                                
990                                                  5                                
991                                                  5                                

    Network ID Start Date (UTC) Submit Date (UTC)      Timestamp Unnamed: 0  \
986        NaN              NaN               NaN   7/8/16 13:01        NaN   
987        NaN              NaN               NaN  7/10/16 23:44        NaN   
989        NaN              NaN               NaN   7/8/16 16:41        NaN   
990        NaN              NaN               NaN   7/8/16 13:07        NaN   
991        NaN              NaN               NaN   7/8/16 12:45        NaN   

    What track are you in?   location track  
986                  Intro  Sunnyvale   NaN  
987                  Games  Sunnyvale   NaN  
989                   Apps  Sunnyvale   NaN  
990                  Games  Sunnyvale   NaN  
991                  Intro  Sunnyvale   NaN

## This question goes on a point scale but each number ends with a "."?

In [15]:
df['How likely is it that you would recommend the Make School Summer Academy to a friend?'].unique()

array([nan, 10.,  9.,  3.,  8.,  6.,  7.,  4.,  5.])

In [16]:
# TODO: Are 10. responses same as 10?
df.replace('10\.', '10', inplace = True, regex = True)
df.replace('9.', '9', inplace = True)
df.replace('8.', '8', inplace = True)
df.replace('7.', '7', inplace = True)
df.replace('6.', '6', inplace = True)
df.replace('5.', '5', inplace = True)
df.replace('4.', '4', inplace = True)
df.replace('3.', '3', inplace = True)
df.replace('2.', '2', inplace = True)
df.replace('1.', '1', inplace = True)

# Sanity check to make sure items were replaced
df['How likely is it that you would recommend the Make School Summer Academy to a friend?'].unique()

array([nan, 10.,  9.,  3.,  8.,  6.,  7.,  4.,  5.])

In [17]:
df['How well are the tutorials paced?'].unique()

array([nan,  3.,  4.,  5.,  2.])

In [18]:
df['How well is the schedule paced?'].unique()

array([3, 4, 1, 2, 5, nan, '2', '3', '4', '5'], dtype=object)

In [19]:
df['How would you rate your overall satisfaction with the Summer Academy this week?'].unique()

array([3, 4, 5, 2, 1, nan, '5', '4', '3'], dtype=object)

In [20]:
df['Network ID'].unique()

array([nan, '3212b7a834', 'f4954355aa', '3d69ca289b', '261608f95d',
       'd6672ddf6f', '088e6f938d', '00f1d07a90', 'e0724aac23',
       '9eeec0f9bf', '6c80fd2754', '6c04cd1a6e', '82eadbe830',
       'ccea45b0f4', '9e894113e2', '7a61b16f29', '55641e8ccb',
       '125a8466ea', '9f88839991', 'bd06f31b2a', '7f24478045',
       '32fdf4fca0', 'ffbbd84b0e', '9dbeedfbf5', '19a8645313',
       '42560fe8ea', 'b194ad4477', 'f8ef38e4e3', '06674df051',
       '66eb19a8df', 'c94ee250b6', '07b48293f4', '258ea0eb2e',
       '81e019676d', 'de5aeb8e84', '58089eb896', '0b7b124ce3',
       '32c6661877', '75a5cf3cee', '5a977a012b', '20eafecabd',
       'e474841bba', 'ae112590e9', 'a578e4964d', '573a652ffb',
       'cadcc3e368', '9ba33ad0f9', '1b349a7cce', '94f319072c',
       '9f09067d6a', '89b8894183', '01074776b4', '11c95dc87f',
       '0d6873c5ed', '8a13f23e89', '830f174273', '9fc69673bd',
       '6d5dece18c', 'f7f5617754', '9500d5b989', 'fe650b21f7',
       'a7deda5bf5', 'a3e21d76e3', '843b902fa2', '

In [21]:
# TODO: See if there are any start dates but not submit date.
df['Start Date (UTC)'].unique()

array([nan, '9/7/16 1:03', '9/7/16 1:04', '9/7/16 1:09', '9/7/16 1:14',
       '9/7/16 1:16', '9/7/16 1:22', '9/7/16 1:28', '9/7/16 1:30',
       '9/7/16 1:47', '9/7/16 1:34', '9/7/16 2:28', '9/7/16 2:39',
       '9/7/16 2:47', '9/7/16 2:56', '9/7/16 2:58', '9/7/16 2:59',
       '9/7/16 3:05', '9/7/16 3:22', '9/7/16 3:15', '9/7/16 3:41',
       '9/7/16 4:04', '9/7/16 4:07', '9/7/16 4:20', '9/7/16 5:41',
       '9/7/16 6:30', '9/7/16 7:55', '9/7/16 10:52', '9/7/16 11:47',
       '9/7/16 9:16', '9/7/16 12:26', '9/7/16 12:45', '9/7/16 13:09',
       '9/7/16 14:39', '9/7/16 14:52', '9/7/16 15:57', '9/7/16 17:11',
       '9/7/16 19:13', '9/7/16 19:23', '9/7/16 19:39', '9/7/16 19:51',
       '9/7/16 23:58', '9/8/16 0:50', '9/8/16 1:55', '9/8/16 5:59',
       '9/8/16 14:25', '9/8/16 22:00', '9/8/16 22:16', '9/8/16 23:06',
       '9/8/16 23:01', '9/9/16 1:41', '9/9/16 4:22', '9/9/16 11:06',
       '9/9/16 13:24', '9/10/16 22:28', '9/12/16 0:05', '9/13/16 4:36',
       '9/7/16 5:08', '9/14/16 1

In [22]:
# TODO: See if there are any submit dates but not start date.
df['Submit Date (UTC)'].unique()

array([nan, '9/7/16 1:04', '9/7/16 1:05', '9/7/16 1:06', '9/7/16 1:11',
       '9/7/16 1:13', '9/7/16 1:14', '9/7/16 1:15', '9/7/16 1:21',
       '9/7/16 1:27', '9/7/16 1:29', '9/7/16 1:33', '9/7/16 1:36',
       '9/7/16 1:50', '9/7/16 1:51', '9/7/16 2:33', '9/7/16 2:41',
       '9/7/16 2:43', '9/7/16 2:50', '9/7/16 2:56', '9/7/16 2:59',
       '9/7/16 3:01', '9/7/16 3:08', '9/7/16 3:31', '9/7/16 3:42',
       '9/7/16 4:05', '9/7/16 4:10', '9/7/16 4:21', '9/7/16 5:43',
       '9/7/16 6:40', '9/7/16 7:58', '9/7/16 10:52', '9/7/16 11:49',
       '9/7/16 12:26', '9/7/16 12:48', '9/7/16 13:10', '9/7/16 14:40',
       '9/7/16 14:54', '9/7/16 15:58', '9/7/16 17:21', '9/7/16 19:25',
       '9/7/16 19:26', '9/7/16 19:40', '9/7/16 19:57', '9/8/16 0:00',
       '9/8/16 0:58', '9/8/16 1:59', '9/8/16 6:04', '9/8/16 14:27',
       '9/8/16 22:06', '9/8/16 22:20', '9/8/16 23:07', '9/8/16 23:11',
       '9/9/16 1:42', '9/9/16 4:25', '9/9/16 11:09', '9/9/16 13:28',
       '9/10/16 22:30', '9/12/16 0:13

In [23]:
# TODO: Combine with Timestamp row
df['Unnamed: 0'].unique()

array([nan, '6/24/16 13:32', '6/24/16 13:48', '6/24/16 13:49',
       '6/24/16 13:53', '6/24/16 13:55', '6/24/16 13:41', '6/24/16 13:46',
       '6/24/16 13:47', '6/24/16 13:50', '6/24/16 13:51', '6/24/16 13:52',
       '6/24/16 13:59', '6/24/16 13:28', '6/24/16 13:31', '6/24/16 13:34',
       '6/24/16 13:39', '6/24/16 13:45', '6/24/16 14:10', '6/24/16 14:12',
       '6/24/16 13:44', '6/24/16 13:54', '6/24/16 13:30', '6/24/16 13:33',
       '6/24/16 14:05'], dtype=object)