In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
FILEPATH = "/Users/raymondmbp/makeschool/DS-1.1-Data-Analysis/datasets/SA_Feedback_Surveys_FINAL/2016"

import os
dir_path = os.path.dirname(os.path.realpath(FILEPATH))
dir_path

# Change default Pandas behavior
pd.set_option('display.max_rows', 500)

# 2016 NPS analysis
## Data Exploration

In [3]:
import glob

all_csvs = glob.glob(os.path.join(FILEPATH, "*.csv"))
read_all_csvs = (pd.read_csv(f) for f in all_csvs)
df = pd.concat(read_all_csvs, ignore_index = True, sort = True)
df.head(5000)

#  \
0    NaN   
1    NaN   
2    NaN   
3    NaN   
4    NaN   
5    NaN   
6    NaN   
7    NaN   
8    NaN   
9    NaN   
10   NaN   
11   NaN   
12   NaN   
13   NaN   
14   NaN   
15   NaN   
16   NaN   
17   NaN   
18   NaN   
19   NaN   
20   NaN   
21   NaN   
22   NaN   
23   NaN   
24   NaN   
25   NaN   
26   NaN   
27   NaN   
28   NaN   
29   NaN   
30   NaN   
31   NaN   
32   NaN   
33   NaN   
34   NaN   
35   NaN   
36   NaN   
37   NaN   
38   NaN   
39   NaN   
40   NaN   
41   NaN   
42   NaN   
43   NaN   
44   NaN   
45   NaN   
46   NaN   
47   NaN   
48   NaN   
49   NaN   
50   NaN   
51   NaN   
52   NaN   
53   NaN   
54   NaN   
55   NaN   
56   NaN   
57   NaN   
58   NaN   
59   NaN   
60   NaN   
61   NaN   
62   NaN   
63   NaN   
64   NaN   
65   NaN   
66   NaN   
67   NaN   
68   NaN   
69   NaN   
70   NaN   
71   NaN   
72   NaN   
73   NaN   
74   NaN   
75   NaN   
76   NaN   
77   NaN   
78   NaN   
79   NaN   
80   NaN   
81   NaN   
82   NaN   
83   NaN   
84   NaN   
85   NaN   
86   NaN   
87   NaN   
88   NaN   
89   NaN   
90   NaN   
91   NaN   
92   NaN   
93   NaN   
94   NaN   
95   NaN   
96   NaN   
97   NaN   
98   NaN   
99   NaN   
100  NaN   
101  NaN   
102  NaN   
103  NaN   
104  NaN   
105  NaN   
106  NaN   
107  NaN   
108  NaN   
109  NaN   
110  NaN   
111  NaN   
112  NaN   
113  NaN   
114  NaN   
115  NaN   
116  NaN   
117  NaN   
118  NaN   
119  NaN   
120  NaN   
121  NaN   
122  NaN   
123  NaN   
124  NaN   
125  NaN   
126  NaN   
127  NaN   
128  NaN   
129  NaN   
130  NaN   
131  NaN   
132  NaN   
133  NaN   
134  NaN   
135  NaN   
136  NaN   
137  NaN   
138  NaN   
139  NaN   
140  NaN   
141  NaN   
142  NaN   
143  NaN   
144  NaN   
145  NaN   
146  NaN   
147  NaN   
148  NaN   
149  NaN   
150  NaN   
151  NaN   
152  NaN   
153  NaN   
154  NaN   
155  NaN   
156  NaN   
157  NaN   
158  NaN   
159  NaN   
160  NaN   
161  NaN   
162  NaN   
163  NaN   
164  NaN   
165  NaN   
166  NaN   
167  NaN   
168  NaN   
169  NaN   
170  NaN   
171  NaN   
172  NaN   
173  NaN   
174  NaN   
175  NaN   
176  NaN   
177  NaN   
178  NaN   
179  NaN   
180  NaN   
181  NaN   
182  NaN   
183  NaN   
184  NaN   
185  NaN   
186  NaN   
187  NaN   
188  NaN   
189  NaN   
190  NaN   
191  NaN   
192  NaN   
193  NaN   
194  NaN   
195  NaN   
196  NaN   
197  NaN   
198  NaN   
199  NaN   
200  NaN   
201  NaN   
202  NaN   
203  NaN   
204  NaN   
205  NaN   
206  NaN   
207  NaN   
208  NaN   
209  NaN   
210  NaN   
211  NaN   
212  NaN   
213  NaN   
214  NaN   
215  NaN   
216  NaN   
217  NaN   
218  NaN   
219  NaN   
220  NaN   
221  NaN   
222  NaN   
223  NaN   
224  NaN   
225  NaN   
226  NaN   
227  NaN   
228  NaN   
229  NaN   
230  NaN   
231  NaN   
232  NaN   
233  NaN   
234  NaN   
235  NaN   
236  NaN   
237  NaN   
238  NaN   
239  NaN   
240  NaN   
241  NaN   
242  NaN   
243  NaN   
244  NaN   
245  NaN   
246  NaN   
247  NaN   
248  NaN   
249  NaN   
..   ...   
742  NaN   
743  NaN   
744  NaN   
745  NaN   
746  NaN   
747  NaN   
748  NaN   
749  NaN   
750  NaN   
751  NaN   
752  NaN   
753  NaN   
754  NaN   
755  NaN   
756  NaN   
757  NaN   
758  NaN   
759  NaN   
760  NaN   
761  NaN   
762  NaN   
763  NaN   
764  NaN   
765  NaN   
766  NaN   
767  NaN   
768  NaN   
769  NaN   
770  NaN   
771  NaN   
772  NaN   
773  NaN   
774  NaN   
775  NaN   
776  NaN   
777  NaN   
778  NaN   
779  NaN   
780  NaN   
781  NaN   
782  NaN   
783  NaN   
784  NaN   
785  NaN   
786  NaN   
787  NaN   
788  NaN   
789  NaN   
790  NaN   
791  NaN   
792  NaN   
793  NaN   
794  NaN   
795  NaN   
796  NaN   
797  NaN   
798  NaN   
799  NaN   
800  NaN   
801  NaN   
802  NaN   
803  NaN   
804  NaN   
805  NaN   
806  NaN   
807  NaN   
808  NaN   
809  NaN   
810  NaN   
811  NaN   
812  NaN   
813  NaN   
814  NaN   
815  NaN   
816  NaN   
817  NaN   
818  NaN   
819  NaN   
820  NaN   
821  NaN   
822  NaN   
823  NaN   

In [4]:
sum_of_pacings = df["How well are the tutorials paced?"].notna().sum() + df["How well is the schedule paced?"].notna().sum() + df["How likely is it that you would recommend the Make School Summer Academy to a friend?"].notna().sum()

print(sum_of_pacings)

992


In [5]:
def clean_pacings(df):
    # Create Pacings column with Schedule and Tutorial Pacings
    # Rename Recommendation Likelihood column to Shorter Name
    # Since you have two different columns with NaNs, map over NaNs and replace with something else
    df["Pacings"]

In [6]:
df.isna().sum()

#                                                                                        927
How likely is it that you would recommend the Make School Summer Academy to a friend?    927
How well are the tutorials paced?                                                        776
How well is the schedule paced?                                                          281
How would you rate your overall satisfaction with the Summer Academy this week?           65
Network ID                                                                               927
Start Date (UTC)                                                                         927
Submit Date (UTC)                                                                        927
Timestamp                                                                                170
Unnamed: 0                                                                               930
What track are you in?                                                

# Plan of attack

- [ ] find out all the answers that don't answer a question and drop those
- [X] append location column to all files https://stackoverflow.com/questions/45211681/add-column-to-csv-file-and-insert-filename-in-that-column
- [X] delete #REF! columns
- [ ] multiply values in questions by 2 to conform with 2017 version
- [ ] combine "What track are you in?" with "track"
- [ ] 4 week program keep

## There's overlap between "What track are you in?" and "track" columns. Combining results

In [7]:
df['track'].unique()

array([nan, 'summerApps', 'summerIntro', 'summerApps (4-week)',
       'summerGames', 'summerVR', 'summerGames (4-week)'], dtype=object)

In [8]:
df['What track are you in?'].unique()

array([nan, 'Intro', 'Games', 'Apps', 'VR', 'Average:'], dtype=object)

## Homogenizing results of two track columns

In [9]:
df.replace('summerApps', 'Apps', inplace = True)
df.replace('summerIntro', 'Intro', inplace = True)
df.replace('summerGames', 'Games', inplace = True)
df.replace('summerVR', 'VR', inplace = True)
df.replace('summerApps (4-week)', 'Apps, Explorer', inplace = True)
df.replace('summerGames (4-week)', 'Games, Explorer', inplace = True)

## Dropping column that was Average: #REF! #REF!

In [10]:
df = df[df["What track are you in?"] != "Average:"]

In [11]:
# Sanity check to make sure items were replaced
df['track'].sort_values().unique()

array(['Apps', 'Games', 'Intro', 'VR', nan], dtype=object)

In [12]:
# Sanity check to make sure items were replaced
df['What track are you in?'].sort_values().unique()

array(['Apps', 'Games', 'Intro', 'VR', nan], dtype=object)

In [21]:
df['What track are you in?'].fillna(df['track'], inplace = True)
df

#  \
0    NaN   
1    NaN   
2    NaN   
3    NaN   
4    NaN   
5    NaN   
6    NaN   
7    NaN   
8    NaN   
9    NaN   
10   NaN   
11   NaN   
12   NaN   
13   NaN   
14   NaN   
15   NaN   
16   NaN   
17   NaN   
18   NaN   
19   NaN   
20   NaN   
21   NaN   
22   NaN   
23   NaN   
24   NaN   
25   NaN   
26   NaN   
27   NaN   
28   NaN   
29   NaN   
30   NaN   
31   NaN   
32   NaN   
33   NaN   
34   NaN   
35   NaN   
36   NaN   
37   NaN   
38   NaN   
39   NaN   
40   NaN   
41   NaN   
42   NaN   
43   NaN   
44   NaN   
45   NaN   
46   NaN   
47   NaN   
48   NaN   
49   NaN   
50   NaN   
51   NaN   
52   NaN   
53   NaN   
54   NaN   
55   NaN   
56   NaN   
57   NaN   
58   NaN   
59   NaN   
60   NaN   
61   NaN   
62   NaN   
63   NaN   
64   NaN   
65   NaN   
66   NaN   
67   NaN   
68   NaN   
69   NaN   
70   NaN   
71   NaN   
72   NaN   
73   NaN   
74   NaN   
75   NaN   
76   NaN   
77   NaN   
78   NaN   
79   NaN   
80   NaN   
81   NaN   
82   NaN   
83   NaN   
84   NaN   
85   NaN   
86   NaN   
87   NaN   
88   NaN   
89   NaN   
90   NaN   
91   NaN   
92   NaN   
93   NaN   
94   NaN   
95   NaN   
96   NaN   
97   NaN   
98   NaN   
99   NaN   
100  NaN   
101  NaN   
102  NaN   
103  NaN   
104  NaN   
105  NaN   
106  NaN   
107  NaN   
108  NaN   
109  NaN   
110  NaN   
111  NaN   
112  NaN   
113  NaN   
114  NaN   
115  NaN   
116  NaN   
117  NaN   
118  NaN   
119  NaN   
120  NaN   
121  NaN   
122  NaN   
123  NaN   
124  NaN   
125  NaN   
126  NaN   
127  NaN   
128  NaN   
129  NaN   
130  NaN   
131  NaN   
132  NaN   
133  NaN   
134  NaN   
135  NaN   
136  NaN   
137  NaN   
138  NaN   
139  NaN   
140  NaN   
141  NaN   
142  NaN   
143  NaN   
144  NaN   
145  NaN   
146  NaN   
147  NaN   
148  NaN   
149  NaN   
150  NaN   
151  NaN   
152  NaN   
153  NaN   
154  NaN   
155  NaN   
156  NaN   
157  NaN   
158  NaN   
159  NaN   
160  NaN   
161  NaN   
162  NaN   
163  NaN   
164  NaN   
165  NaN   
166  NaN   
167  NaN   
168  NaN   
169  NaN   
170  NaN   
171  NaN   
172  NaN   
173  NaN   
174  NaN   
175  NaN   
176  NaN   
177  NaN   
178  NaN   
179  NaN   
180  NaN   
181  NaN   
182  NaN   
183  NaN   
184  NaN   
185  NaN   
186  NaN   
187  NaN   
188  NaN   
189  NaN   
190  NaN   
191  NaN   
192  NaN   
193  NaN   
194  NaN   
195  NaN   
196  NaN   
197  NaN   
198  NaN   
199  NaN   
200  NaN   
201  NaN   
202  NaN   
203  NaN   
204  NaN   
205  NaN   
206  NaN   
207  NaN   
208  NaN   
209  NaN   
210  NaN   
211  NaN   
212  NaN   
213  NaN   
214  NaN   
215  NaN   
216  NaN   
217  NaN   
218  NaN   
219  NaN   
220  NaN   
221  NaN   
222  NaN   
223  NaN   
224  NaN   
225  NaN   
226  NaN   
227  NaN   
228  NaN   
229  NaN   
230  NaN   
231  NaN   
232  NaN   
233  NaN   
234  NaN   
235  NaN   
236  NaN   
237  NaN   
238  NaN   
239  NaN   
240  NaN   
241  NaN   
242  NaN   
243  NaN   
244  NaN   
245  NaN   
246  NaN   
247  NaN   
248  NaN   
249  NaN   
..   ...   
741  NaN   
742  NaN   
743  NaN   
744  NaN   
745  NaN   
746  NaN   
747  NaN   
748  NaN   
749  NaN   
750  NaN   
751  NaN   
752  NaN   
753  NaN   
754  NaN   
755  NaN   
756  NaN   
757  NaN   
758  NaN   
759  NaN   
760  NaN   
761  NaN   
762  NaN   
763  NaN   
764  NaN   
765  NaN   
766  NaN   
767  NaN   
768  NaN   
769  NaN   
770  NaN   
771  NaN   
772  NaN   
773  NaN   
774  NaN   
775  NaN   
776  NaN   
777  NaN   
778  NaN   
779  NaN   
780  NaN   
781  NaN   
782  NaN   
783  NaN   
784  NaN   
785  NaN   
786  NaN   
787  NaN   
788  NaN   
789  NaN   
790  NaN   
791  NaN   
792  NaN   
793  NaN   
794  NaN   
795  NaN   
796  NaN   
797  NaN   
798  NaN   
799  NaN   
800  NaN   
801  NaN   
802  NaN   
803  NaN   
804  NaN   
805  NaN   
806  NaN   
807  NaN   
808  NaN   
809  NaN   
810  NaN   
811  NaN   
812  NaN   
813  NaN   
814  NaN   
815  NaN   
816  NaN   
817  NaN   
818  NaN   
819  NaN   
820  NaN   
821  NaN   
822  NaN   

In [22]:
df.loc[df['track'] == "Games"]

#  \
412  27a63d6c24710feb52c0cfdef7e01175   
414  828fafa477484f61d2ca5930fe99ad46   
415  7d70f1e30217d867f3c0f961462d8ae8   
419  5ee2a5d8e87fd5790906f7b004963e14   
421  ea85e7c699751b5993776ef16db0b1d9   
422  58cb61ce774b116d87e3888d4c1babf1   
426  785568c94d73aa0fad4493ee79fa3974   
428  6e2c750a71613e3fd7d5f425320cc750   
429  522ff7a7546272c3c98eab026e8c098a   
433  bb261d3e5b4fe2197f54f28c416948e1   
434  391157a49dc832edb535b3c6ee3dd6a0   
437  3b728045b33cb55602c8587e046f45cf   
450  c2bc67325eb91085f3686aabf309d801   
453  143652af47062192767081ff1dd630cc   
455  3c3495614eada68b5fa8e19377e1cccd   
456  8e2309e3a1ba2a5630ea251b96712a9a   
463  50f1c0545d9cef1c10be657e1083990d   
464  22ac2ab300a76178ce53104d03408c8a   
467  d353c2cdff6bcf3e932579a5647d511a   
469  951e9361c4da1756ae1c6fb2612cb9dd   

     How likely is it that you would recommend the Make School Summer Academy to a friend?  \
412                                                3.0                                       
414                                                9.0                                       
415                                               10.0                                       
419                                                8.0                                       
421                                                9.0                                       
422                                               10.0                                       
426                                               10.0                                       
428                                                9.0                                       
429                                               10.0                                       
433                                                7.0                                       
434                                               10.0                                       
437                                                5.0                                       
450                                               10.0                                       
453                                               10.0                                       
455                                               10.0                                       
456                                                8.0                                       
463                                               10.0                                       
464                                                8.0                                       
467                                               10.0                                       
469                                                9.0                                       

     How well are the tutorials paced? How well is the schedule paced?  \
412                                NaN                             NaN   
414                                NaN                             NaN   
415                                NaN                             NaN   
419                                NaN                             NaN   
421                                NaN                             NaN   
422                                NaN                             NaN   
426                                NaN                             NaN   
428                                NaN                             NaN   
429                                NaN                             NaN   
433                                NaN                             NaN   
434                                NaN                             NaN   
437                                NaN                             NaN   
450                                NaN                             NaN   
453                                NaN                             NaN   
455                                NaN                             NaN   
456            

In [15]:
# def combine_tracks(df):
#     df["track"] = df["track"].fillna(",No Location")
#     df["What track are you in?"] = df["What track are you in?"].fillna("No Location")
#     df["Track_Full"] = df["What track are you in?"] + df["track"]
# #     df.drop(columns=["What track are you in?", "track"], inplace=True)
#     return df

In [16]:
# df = combine_tracks(df)

In [17]:
# TODO: Merge two columns
# df = df['track'].combine_first(df['What track are you in?'])


# df = pd.merge(df['What track are you in?'], df['track'], on='What track are you in?', how='outer')

# for index, item in enumerate(df["Track_Full"]):
#     if item == "No LocationNo Location":
#         print(index, item)

# df.merge(df['What track are you in?'], df['track'], on='What track are you in?', how='outer')
# df.concat([df['What track are you in?'], df['track']], axis = 1, ignore_index = True, sort = True)


# pd.DataFrame({'Column1': pd.merge(df['What track are you in?'], df['track'])}).sort_index()


# {"a": 0, "b": 1}
# {"each location": int(some number), "No Location/NaN": 0}

# [a, b, b, a, b]
# -->
# [0, 1, 1, 0, 1]

In [18]:
df.head()

#  \
0  NaN   
1  NaN   
2  NaN   
3  NaN   
4  NaN   

   How likely is it that you would recommend the Make School Summer Academy to a friend?  \
0                                                NaN                                       
1                                                NaN                                       
2                                                NaN                                       
3                                                NaN                                       
4                                                NaN                                       

   How well are the tutorials paced? How well is the schedule paced?  \
0                                NaN                               3   
1                                NaN                               3   
2                                NaN                               3   
3                                NaN                               4   
4                                NaN                               4   

  How would you rate your overall satisfaction with the Summer Academy this week?  \
0                                                  3                                
1                                                  4                                
2                                                  4                                
3                                                  4                                
4                                                  5                                

  Network ID Start Date (UTC) Submit Date (UTC)    Timestamp Unnamed: 0  \
0        NaN              NaN               NaN  8/5/16 1:39        NaN   
1        NaN              NaN               NaN  8/5/16 1:40        NaN   
2        NaN              NaN               NaN  8/5/16 1:40        NaN   
3        NaN              NaN               NaN  8/5/16 1:42        NaN   
4        NaN              NaN               NaN  8/5/16 1:45        NaN   

  What track are you in? location track  
0                    NaN   Taipei   NaN  
1                    NaN   Taipei   NaN  
2                    NaN   Taipei   NaN  
3                    NaN   Taipei   NaN  
4                    NaN   Taipei   NaN

In [19]:
def get_track(string):
    possible_tracks = string.split(',')
    if possible_tracks[0] == "No Location" and possible_tracks[0] == "No Location":
        return "No Location"

SyntaxError: invalid syntax (<ipython-input-20-e5cded783f20>, line 1)

## This question goes on a point scale but each number ends with a "."?

In [23]:
df['How likely is it that you would recommend the Make School Summer Academy to a friend?'].unique()

array([nan, 10.,  9.,  3.,  8.,  6.,  7.,  4.,  5.])

In [24]:
# TODO: Are 10. responses same as 10?
df.replace('10.0', '10', inplace = True)
df.replace('9.0', '9', inplace = True)
df.replace('8.0', '8', inplace = True)
df.replace('7.0', '7', inplace = True)
df.replace('6.0', '6', inplace = True)
df.replace('5.0', '5', inplace = True)
df.replace('4.0', '4', inplace = True)
df.replace('3.0', '3', inplace = True)
df.replace('2.0', '2', inplace = True)
df.replace('1.0', '1', inplace = True)

# Sanity check to make sure items were replaced
df['How likely is it that you would recommend the Make School Summer Academy to a friend?'].unique()

array([nan, 10.,  9.,  3.,  8.,  6.,  7.,  4.,  5.])

In [25]:
df['How well are the tutorials paced?'].unique()

array([nan,  3.,  4.,  5.,  2.])

In [26]:
df['How well is the schedule paced?'].unique()

array([3, 4, 1, 2, 5, nan, '2', '3', '4', '5'], dtype=object)

In [27]:
df['How would you rate your overall satisfaction with the Summer Academy this week?'].unique()

array([3, 4, 5, 2, 1, nan, '5', '4', '3'], dtype=object)

In [28]:
df['Network ID'].unique()

array([nan, '3212b7a834', 'f4954355aa', '3d69ca289b', '261608f95d',
       'd6672ddf6f', '088e6f938d', '00f1d07a90', 'e0724aac23',
       '9eeec0f9bf', '6c80fd2754', '6c04cd1a6e', '82eadbe830',
       'ccea45b0f4', '9e894113e2', '7a61b16f29', '55641e8ccb',
       '125a8466ea', '9f88839991', 'bd06f31b2a', '7f24478045',
       '32fdf4fca0', 'ffbbd84b0e', '9dbeedfbf5', '19a8645313',
       '42560fe8ea', 'b194ad4477', 'f8ef38e4e3', '06674df051',
       '66eb19a8df', 'c94ee250b6', '07b48293f4', '258ea0eb2e',
       '81e019676d', 'de5aeb8e84', '58089eb896', '0b7b124ce3',
       '32c6661877', '75a5cf3cee', '5a977a012b', '20eafecabd',
       'e474841bba', 'ae112590e9', 'a578e4964d', '573a652ffb',
       'cadcc3e368', '9ba33ad0f9', '1b349a7cce', '94f319072c',
       '9f09067d6a', '89b8894183', '01074776b4', '11c95dc87f',
       '0d6873c5ed', '8a13f23e89', '830f174273', '9fc69673bd',
       '6d5dece18c', 'f7f5617754', '9500d5b989', 'fe650b21f7',
       'a7deda5bf5', 'a3e21d76e3', '843b902fa2', '

In [29]:
# TODO: See if there are any start dates but not submit date.
df['Start Date (UTC)'].unique()

array([nan, '9/7/16 1:03', '9/7/16 1:04', '9/7/16 1:09', '9/7/16 1:14',
       '9/7/16 1:16', '9/7/16 1:22', '9/7/16 1:28', '9/7/16 1:30',
       '9/7/16 1:47', '9/7/16 1:34', '9/7/16 2:28', '9/7/16 2:39',
       '9/7/16 2:47', '9/7/16 2:56', '9/7/16 2:58', '9/7/16 2:59',
       '9/7/16 3:05', '9/7/16 3:22', '9/7/16 3:15', '9/7/16 3:41',
       '9/7/16 4:04', '9/7/16 4:07', '9/7/16 4:20', '9/7/16 5:41',
       '9/7/16 6:30', '9/7/16 7:55', '9/7/16 10:52', '9/7/16 11:47',
       '9/7/16 9:16', '9/7/16 12:26', '9/7/16 12:45', '9/7/16 13:09',
       '9/7/16 14:39', '9/7/16 14:52', '9/7/16 15:57', '9/7/16 17:11',
       '9/7/16 19:13', '9/7/16 19:23', '9/7/16 19:39', '9/7/16 19:51',
       '9/7/16 23:58', '9/8/16 0:50', '9/8/16 1:55', '9/8/16 5:59',
       '9/8/16 14:25', '9/8/16 22:00', '9/8/16 22:16', '9/8/16 23:06',
       '9/8/16 23:01', '9/9/16 1:41', '9/9/16 4:22', '9/9/16 11:06',
       '9/9/16 13:24', '9/10/16 22:28', '9/12/16 0:05', '9/13/16 4:36',
       '9/7/16 5:08', '9/14/16 1

In [30]:
# TODO: See if there are any submit dates but not start date.
df['Submit Date (UTC)'].unique()

array([nan, '9/7/16 1:04', '9/7/16 1:05', '9/7/16 1:06', '9/7/16 1:11',
       '9/7/16 1:13', '9/7/16 1:14', '9/7/16 1:15', '9/7/16 1:21',
       '9/7/16 1:27', '9/7/16 1:29', '9/7/16 1:33', '9/7/16 1:36',
       '9/7/16 1:50', '9/7/16 1:51', '9/7/16 2:33', '9/7/16 2:41',
       '9/7/16 2:43', '9/7/16 2:50', '9/7/16 2:56', '9/7/16 2:59',
       '9/7/16 3:01', '9/7/16 3:08', '9/7/16 3:31', '9/7/16 3:42',
       '9/7/16 4:05', '9/7/16 4:10', '9/7/16 4:21', '9/7/16 5:43',
       '9/7/16 6:40', '9/7/16 7:58', '9/7/16 10:52', '9/7/16 11:49',
       '9/7/16 12:26', '9/7/16 12:48', '9/7/16 13:10', '9/7/16 14:40',
       '9/7/16 14:54', '9/7/16 15:58', '9/7/16 17:21', '9/7/16 19:25',
       '9/7/16 19:26', '9/7/16 19:40', '9/7/16 19:57', '9/8/16 0:00',
       '9/8/16 0:58', '9/8/16 1:59', '9/8/16 6:04', '9/8/16 14:27',
       '9/8/16 22:06', '9/8/16 22:20', '9/8/16 23:07', '9/8/16 23:11',
       '9/9/16 1:42', '9/9/16 4:25', '9/9/16 11:09', '9/9/16 13:28',
       '9/10/16 22:30', '9/12/16 0:13

In [31]:
# TODO: Combine with Timestamp row
df['Unnamed: 0'].unique()

array([nan, '6/24/16 13:32', '6/24/16 13:48', '6/24/16 13:49',
       '6/24/16 13:53', '6/24/16 13:55', '6/24/16 13:41', '6/24/16 13:46',
       '6/24/16 13:47', '6/24/16 13:50', '6/24/16 13:51', '6/24/16 13:52',
       '6/24/16 13:59', '6/24/16 13:28', '6/24/16 13:31', '6/24/16 13:34',
       '6/24/16 13:39', '6/24/16 13:45', '6/24/16 14:10', '6/24/16 14:12',
       '6/24/16 13:44', '6/24/16 13:54', '6/24/16 13:30', '6/24/16 13:33',
       '6/24/16 14:05'], dtype=object)

# 2017 NPS Analysis
## Data Exploration

In [32]:
FILEPATH2 = "/Users/raymondmbp/makeschool/DS-1.1-Data-Analysis/datasets/SA_Feedback_Surveys_FINAL/2017"

In [33]:
df2 = pd.read_csv("/Users/raymondmbp/makeschool/DS-1.1-Data-Analysis/datasets/SA_Feedback_Surveys_FINAL/2017/Student Feedback Surveys-Superview.csv")

In [34]:
df2.sort_values(by="ID").head(500)

ID       Location            Track    Week Rating (Num)  \
96     8        Atlanta   Apps, Explorer  Week 1            8   
97     9        Atlanta             Apps  Week 1            8   
98    10        Atlanta   Apps, Explorer  Week 1            8   
256   11        Atlanta   Apps, Explorer  Week 1            9   
376   12        Atlanta             Apps  Week 1           10   
377   13        Atlanta   Apps, Explorer  Week 1           10   
99    14        Atlanta             Apps  Week 1            8   
257   15   Redwood City             Apps  Week 1            9   
100   16   Redwood City             Apps  Week 1            8   
378   17   Redwood City             Apps  Week 1           10   
101   18  San Francisco   Apps, Explorer  Week 1            8   
379   19   Redwood City             Apps  Week 1           10   
44    20   Redwood City             Apps  Week 1            7   
102   21   Redwood City             Apps  Week 1            8   
380   22   Redwood City             Apps  Week 1           10   
5     23   Redwood City             Apps  Week 1            5   
381   24   Redwood City             Apps  Week 1           10   
103   25   Redwood City             Apps  Week 1            8   
45    26    Los Angeles             Apps  Week 1            7   
258   27    Los Angeles            Games  Week 1            9   
6     28    Los Angeles             Apps  Week 7            5   
104   29    Los Angeles             Apps  Week 1            8   
259   30    Los Angeles             Apps  Week 1            9   
105   31    Los Angeles            Games  Week 1            8   
260   32    Los Angeles             Apps  Week 1            9   
261   33    Los Angeles            Games  Week 1            9   
382   34    Los Angeles             Apps  Week 1           10   
46    35    Los Angeles             Apps  Week 1            7   
1     36    Los Angeles             Apps  Week 1            4   
20    37    Los Angeles            Games  Week 1            6   
47    38        Chicago             Apps  Week 1            7   
106   39        Chicago             Apps  Week 1            8   
107   40        Chicago             Apps  Week 1            8   
21    41        Chicago   Apps, Explorer  Week 1            6   
383   42        Chicago             Apps  Week 1           10   
384   43        Chicago   Apps, Explorer  Week 1           10   
385   44        Chicago             Apps  Week 1           10   
22    45        Chicago             Apps  Week 1            6   
108   46        Chicago   Apps, Explorer  Week 1            8   
23    47        Chicago             Apps  Week 1            6   
48    48  San Francisco               VR  Week 1            7   
386   49  San Francisco               VR  Week 1           10   
387   50  San Francisco               VR  Week 1           10   
388   51  San Francisco               VR  Week 1           10   
389   52  San Francisco               VR  Week 1           10   
109   53  San Francisco               VR  Week 1            8   
390   54  San Francisco               VR  Week 1           10   
110   55  San Francisco               VR  Week 1            8   
262   56  San Francisco               VR  Week 1            9   
391   57  San Francisco               VR  Week 1           10   
111   58  San Francisco             Apps  Week 1            8   
263   59  San Francisco             Apps  Week 1            9   
264   60  San Francisco             Apps  Week 1            9   
112   61  San Francisco             Apps  Week 1            8   
49    62  San Francisco             Apps  Week 1            7   
113   63  San Francisco             Apps  Week 1            8   
392   64  San Francisco             Apps  Week 1           10   
7     65  San Francisco             Apps  Week 1            5   
393   66  San Francisco             Apps  Week 1           10   
50    67  San Francisco             Apps  Week 1            7   
265   68  San Francisco             Apps 

In [35]:
df2.isna().sum()

ID                  0
Location           47
Track              47
Week                0
Rating (Num)        0
Schedule Pacing     3
dtype: int64

# Plan of attack
- [X] Remove "Week" from Week column to only get numbers. Should make for easier graphing/drawing of conclusions
- [ ] What are explorer categories?
- [X] Remove #ERROR! column
- [ ] (OPTIONAL) Associate values in schedule pacing with numbers?
- [ ] (OPTIONAL) Fill values of Track, location, schedule with not specified

In [36]:
df2['Location'].unique()

array(['San Francisco', 'Los Angeles', nan, 'New York City',
       'Redwood City', 'Santa Clara', 'Oakland', 'Washington DC',
       'Chicago', 'Atlanta', 'Hong Kong', 'Beijing', 'Tokyo'],
      dtype=object)

In [37]:
df2['Track'].unique()

array(['Apps, Explorer', 'Apps', 'Games', nan, 'VR', 'Games, Explorer'],
      dtype=object)

In [38]:
df2['Week'].unique()

array(['Week 1', 'Week 2', 'Week 7', 'Week 3', 'Week 4', 'Week 5',
       'Week 6', 'Week 8'], dtype=object)

In [39]:
df2['Week'].replace('Week\s+', '', regex = True, inplace = True)
df2

ID       Location            Track Week Rating (Num)  \
0      134  San Francisco   Apps, Explorer    1            3   
1       36    Los Angeles             Apps    1            4   
2      117  San Francisco            Games    1            4   
3      253            NaN              NaN    2            4   
4      350  New York City   Apps, Explorer    1            4   
5       23   Redwood City             Apps    1            5   
6       28    Los Angeles             Apps    7            5   
7       65  San Francisco             Apps    1            5   
8      101    Santa Clara             Apps    1            5   
9      124    Santa Clara             Apps    1            5   
10     157   Redwood City             Apps    2            5   
11     170        Oakland             Apps    2            5   
12     255  San Francisco             Apps    2            5   
13     289  Washington DC             Apps    1            5   
14     299  Washington DC   Apps, Explorer    1            5   
15     307            NaN              NaN    3            5   
16     319   Redwood City             Apps    3            5   
17     336  New York City             Apps    1            5   
18     441  San Francisco   Apps, Explorer    3            5   
19     482    Santa Clara             Apps    3            5   
20      37    Los Angeles            Games    1            6   
21      41        Chicago   Apps, Explorer    1            6   
22      45        Chicago             Apps    1            6   
23      47        Chicago             Apps    1            6   
24      77  San Francisco             Apps    1            6   
25      78  San Francisco             Apps    1            6   
26      94  San Francisco   Apps, Explorer    1            6   
27     193    Santa Clara             Apps    2            6   
28     251  San Francisco   Apps, Explorer    2            6   
29     254  San Francisco             Apps    2            6   
30     276    Santa Clara             Apps    2            6   
31     294  Washington DC             Apps    1            6   
32     314   Redwood City             Apps    3            6   
33     340            NaN              NaN    1            6   
34     347  New York City            Games    1            6   
35     349  New York City             Apps    1            6   
36     397    Santa Clara            Games    3            6   
37     429    Santa Clara             Apps    3            6   
38     438  San Francisco   Apps, Explorer    3            6   
39     452  San Francisco             Apps    3            6   
40     455  San Francisco   Apps, Explorer    3            6   
41     472  San Francisco             Apps    3            6   
42     484        Oakland             Apps    3            6   
43     489            NaN              NaN    1            6   
44      20   Redwood City             Apps    1            7   
45      26    Los Angeles             Apps    1            7   
46      35    Los Angeles             Apps    1            7   
47      38        Chicago             Apps    1            7   
48      48  San Francisco               VR    1            7   
49      62  San Francisco             Apps    1            7   
50      67  San Francisco             Apps    1            7   
51      72  San Francisco             Apps    1            7   
52      75  San Francisco             Apps    1            7   
53      85    Santa Clara             Apps    1            7   
54      87  San Francisco             Apps    1            7   
55     104  San Francisco   Apps, Explorer    1            7   
56     107  San Francisco            Games    1            7   
57     118  San Francisco   Apps, Explorer    1            7   
58     122    Santa Clara             Apps    1            7   
59     136  San Francisco   Apps, Explorer    1            7   
60     140  San Francisco   Apps, Explorer    1            7   
61     155  San Francisco             Ap

In [40]:
df2['Rating (Num)'].unique()

array(['3', '4', '5', '6', '7', '8', '9', '10', '0', '1', '2', '#ERROR!'],
      dtype=object)

## Checking to see what the #ERROR! columns are

In [41]:
df2[df2['Rating (Num)'].str.match('#ERROR!')]

ID Location Track Week Rating (Num) Schedule Pacing
1310  1356      NaN   NaN    2      #ERROR!             NaN
1322  1368      NaN   NaN    3      #ERROR!             NaN
1411  1458      NaN   NaN    3      #ERROR!             NaN

In [42]:
df2 = df2[df2['Rating (Num)'] != '#ERROR!']
df2['Rating (Num)'].unique()

array(['3', '4', '5', '6', '7', '8', '9', '10', '0', '1', '2'],
      dtype=object)

In [ ]:
df2['Schedule Pacing'].unique()

In [ ]:
df2